# Site settings
email: ''
baseurl: ''
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-89033402-1

# SEO settings
title: Head Over Reels
description: Film Reviews by Brady Findell
url: "http://www.headoverreals.com"
twitter_username:
default_img:

collections:
  videos:
    output: true

# Profile settings
name: Brady Findell
profile_img:
profile:
social:
  github:

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
